<?php
/**
 * Quizly installer — WordPress-style "fill the form, click install".
 *
 * Standalone (does not go through the router). Run by visiting /install.php
 * in a browser. It:
 *   1. Collects DB credentials + admin account
 *   2. Tests the DB connection (creates the MySQL database if missing)
 *   3. Writes config.php
 *   4. Creates all tables
 *   5. Creates the first super-admin
 *
 * Safe to re-run: if config.php exists and is installed, it warns first.
 */

declare(strict_types=1);
error_reporting(E_ALL & ~E_DEPRECATED & ~E_NOTICE);

require __DIR__ . '/includes/db.php';
require __DIR__ . '/includes/schema.php';

$configPath = __DIR__ . '/config.php';
$alreadyInstalled = false;
if (is_file($configPath)) {
    $existing = require $configPath;
    $alreadyInstalled = !empty($existing['installed']);
}

$errors = [];
$done = false;

function h($s) { return htmlspecialchars((string)($s ?? ''), ENT_QUOTES, 'UTF-8'); }

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $driver = $_POST['db_driver'] ?? 'mysql';
    $cfg = [
        'db_driver'   => $driver,
        'db_host'     => trim($_POST['db_host'] ?? 'localhost'),
        'db_port'     => (int)($_POST['db_port'] ?? 3306),
        'db_name'     => trim($_POST['db_name'] ?? 'quizforge'),
        'db_user'     => trim($_POST['db_user'] ?? 'root'),
        'db_pass'     => (string)($_POST['db_pass'] ?? ''),
        'db_charset'  => 'utf8mb4',
        'sqlite_path' => __DIR__ . '/data/quizforge.sqlite',
        'app_name'    => 'Quizly',
        'app_tagline' => 'Online Quiz, Exam & Poll Maker',
        'secret_key'  => bin2hex(random_bytes(24)),
        'base_url'    => trim($_POST['base_url'] ?? ''),
        'smtp_host'   => '', 'smtp_port' => 587, 'smtp_user' => '', 'smtp_pass' => '',
        'smtp_from'   => 'no-reply@example.com', 'smtp_secure' => 'tls',
        'anthropic_api_key' => '', 'openai_api_key' => '',
        'installed'   => true,
    ];

    $adminEmail = strtolower(trim($_POST['admin_email'] ?? ''));
    $adminPass  = (string)($_POST['admin_pass'] ?? '');
    $adminName  = trim($_POST['admin_name'] ?? 'Admin');

    if (!filter_var($adminEmail, FILTER_VALIDATE_EMAIL)) {
        $errors[] = 'Enter a valid admin email.';
    }
    if (strlen($adminPass) < 6) {
        $errors[] = 'Admin password must be at least 6 characters.';
    }

    if (!$errors) {
        try {
            if ($driver === 'mysql') {
                // Create the database if it doesn't exist, then connect to it.
                $server = DB::serverConnect($cfg);
                $server->exec("CREATE DATABASE IF NOT EXISTS `{$cfg['db_name']}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            }
            DB::boot($cfg);
            create_schema();

            // First user = super admin
            $hash = password_hash($adminPass, PASSWORD_BCRYPT);
            DB::run(
                "INSERT INTO users(email, password_hash, name, created_at, is_super_admin, is_approved)
                 VALUES(?,?,?,?,1,1)",
                [$adminEmail, $hash, $adminName, time()]
            );

            // Write config.php
            $php = "<?php\n// Generated by Quizly installer on " . date('c') . "\nreturn " . var_export($cfg, true) . ";\n";
            if (@file_put_contents($configPath, $php) === false) {
                $errors[] = 'Could not write config.php — check folder permissions (must be writable).';
            } else {
                $done = true;
            }
        } catch (Throwable $ex) {
            $errors[] = 'Setup failed: ' . $ex->getMessage();
        }
    }
}
?><!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Install Quizly</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-100 min-h-screen py-8 px-4">
  <div class="max-w-lg mx-auto">
    <div class="flex items-center gap-2 justify-center mb-6">
      <span class="inline-block w-9 h-9 rounded bg-indigo-600 text-white grid place-items-center font-bold">Q</span>
      <h1 class="text-2xl font-bold text-slate-900">Quizly Installer</h1>
    </div>

    <?php if ($done): ?>
      <div class="bg-white border border-emerald-200 rounded-xl p-6 text-center shadow-sm">
        <div class="text-4xl mb-2">🎉</div>
        <h2 class="text-xl font-bold text-slate-900 mb-2">Installed successfully</h2>
        <p class="text-sm text-slate-600 mb-4">Your database is set up and your admin account is ready.</p>
        <p class="text-xs text-red-600 mb-4"><b>Important:</b> delete <code>install.php</code> from the server now, for security.</p>
        <a href="./" class="inline-block px-5 py-2.5 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 font-medium">Go to Quizly →</a>
      </div>
    <?php elseif ($alreadyInstalled && $_SERVER['REQUEST_METHOD'] !== 'POST'): ?>
      <div class="bg-white border border-amber-200 rounded-xl p-6 shadow-sm">
        <h2 class="text-lg font-bold text-slate-900 mb-2">⚠ Already installed</h2>
        <p class="text-sm text-slate-600 mb-4">A <code>config.php</code> already exists. Re-installing will create a NEW admin and re-run the schema (existing tables are kept). For security you should delete <code>install.php</code>.</p>
        <a href="./" class="text-indigo-700 hover:underline text-sm">Go to the app instead →</a>
        <details class="mt-4"><summary class="text-sm text-slate-500 cursor-pointer">Re-install anyway</summary>
          <p class="text-xs text-slate-500 mt-2">Scroll down and submit the form to proceed.</p>
        </details>
      </div>
    <?php endif; ?>

    <?php if (!$done): ?>
      <?php if ($errors): ?>
        <div class="bg-red-50 border border-red-200 text-red-800 rounded-lg p-3 mb-4 text-sm">
          <?php foreach ($errors as $er): ?><p>• <?= h($er) ?></p><?php endforeach; ?>
        </div>
      <?php endif; ?>

      <form method="post" class="bg-white border border-slate-200 rounded-xl p-6 space-y-4 shadow-sm">
        <div>
          <h2 class="font-semibold text-slate-900 mb-1">Database</h2>
          <p class="text-xs text-slate-500 mb-3">Use the MySQL details from your hosting control panel (cPanel → MySQL Databases). For a quick local test, choose SQLite — no credentials needed.</p>
          <label class="block text-sm mb-2">Engine
            <select name="db_driver" class="w-full mt-1 px-3 py-2 border border-slate-300 rounded" onchange="document.getElementById('mysql-fields').style.display=this.value==='mysql'?'block':'none'">
              <option value="mysql">MySQL (shared hosting / production)</option>
              <option value="sqlite">SQLite (local test, zero setup)</option>
            </select>
          </label>
          <div id="mysql-fields" class="space-y-2">
            <div class="grid grid-cols-3 gap-2">
              <label class="col-span-2 text-sm">Host<input name="db_host" value="localhost" class="w-full mt-1 px-3 py-2 border border-slate-300 rounded" /></label>
              <label class="text-sm">Port<input name="db_port" value="3306" class="w-full mt-1 px-3 py-2 border border-slate-300 rounded" /></label>
            </div>
            <label class="block text-sm">Database name<input name="db_name" value="quizforge" class="w-full mt-1 px-3 py-2 border border-slate-300 rounded" /></label>
            <label class="block text-sm">DB username<input name="db_user" value="root" class="w-full mt-1 px-3 py-2 border border-slate-300 rounded" /></label>
            <label class="block text-sm">DB password<input type="password" name="db_pass" class="w-full mt-1 px-3 py-2 border border-slate-300 rounded" /></label>
          </div>
        </div>

        <div class="border-t border-slate-200 pt-4">
          <h2 class="font-semibold text-slate-900 mb-1">Admin account</h2>
          <p class="text-xs text-slate-500 mb-3">This first account becomes the super-admin.</p>
          <label class="block text-sm mb-2">Your name<input name="admin_name" value="Admin" class="w-full mt-1 px-3 py-2 border border-slate-300 rounded" /></label>
          <label class="block text-sm mb-2">Email<input type="email" name="admin_email" required class="w-full mt-1 px-3 py-2 border border-slate-300 rounded" /></label>
          <label class="block text-sm">Password (min 6)<input type="password" name="admin_pass" required minlength="6" class="w-full mt-1 px-3 py-2 border border-slate-300 rounded" /></label>
        </div>

        <div class="border-t border-slate-200 pt-4">
          <label class="block text-sm">Site URL <span class="text-slate-400">(optional — auto-detected if blank)</span>
            <input name="base_url" placeholder="https://yourdomain.com" class="w-full mt-1 px-3 py-2 border border-slate-300 rounded" />
          </label>
        </div>

        <button class="w-full py-2.5 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 font-medium">Install Quizly</button>
      </form>
    <?php endif; ?>
  </div>
</body>
</html>
